decorators/auth.py
from functools import wraps
from flask import session, redirect, url_for

def requires_login(f):
    @wraps(f)
    def decorator(*args, **kwargs):
        if ("username" not in session and "id" not in session):
            return redirect(url_for("localauth.login"))
        else:
            return f(*args, **kwargs)
    return decorator

routes/group.py
from flask import Blueprint
from controllers.group import GroupController
from decorators.auth import requires_login
from flask_jwt_extended import jwt_required

bp = Blueprint("group", __name__, url_prefix="/group")

groupController = GroupController()

@bp.get("/")
def getAll ():
    return groupController.getAll()

# WHEN USER IS LOGGED

@bp.post("/")
@jwt_required()
def create ():
    return groupController.create()

@bp.get("/add/<int:id>/<role>")
@jwt_required()
def addPerson (id,role):
    return groupController.addPerson(id, role)


@bp.get("/user")
@jwt_required()
def getByUser():
    return groupController.getByUser()

#ADMIN

@bp.get("/changevisibility/<int:id>")
@requires_login
def changeVisibility(id):
    return groupController.changeVisibility(id)

@bp.get("/dashboard")
@requires_login
def dashboard():
    return groupController.dashboard()

@bp.get("/delete/<int:id>")
@requires_login
def delete(id):
    return groupController.delete(id)

templates/auth.html
{% extends "layouts/layout.html" %}
{% block children %}
<main class="space-y-6 flex flex-col items-center w-full">
    <header class="w-full max-w-xl text-center space-y-2">
        <h1 class="text-2xl font-semibold">Inicia sesión</h1>
        <p class="text-sm text-neutral-400">
            Este espacio es solo para administradores, si no eres uno de ellos, no
            ingreses.
        </p>
    </header>
    <form method="POST" class="max-w-xl space-y-4 w-full">
        <label class="input input-bordered flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="h-4 w-4 opacity-70">
                <path
                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM12.735 14c.618 0 1.093-.561.872-1.139a6.002 6.002 0 0 0-11.215 0c-.22.578.254 1.139.872 1.139h9.47Z" />
            </svg>
            <input type="text" name="username" class="grow" placeholder="Usuario" />
        </label>
        <label class="input input-bordered flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="h-4 w-4 opacity-70">
                <path fill-rule="evenodd"
                    d="M14 6a4 4 0 0 1-4.899 3.899l-1.955 1.955a.5.5 0 0 1-.353.146H5v1.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2.293a.5.5 0 0 1 .146-.353l3.955-3.955A4 4 0 1 1 14 6Zm-4-2a.75.75 0 0 0 0 1.5.5.5 0 0 1 .5.5.75.75 0 0 0 1.5 0 2 2 0 0 0-2-2Z"
                    clip-rule="evenodd" />
            </svg>
            <input type="password" name="password" class="grow" placeholder="Contraseña" />
        </label>
        <div>
            <button class="btn btn-primary">Inicia sesión</button>
        </div>
    </form>
</main>
{% endblock %}

templates/index.html
{% extends "layouts/layout.html" %}
{% block children %}
<header class="space-y-2">
    <h1 class="text-2xl font-semibold">Camina Seguro</h1>
    <h2 class="text-sm">Dashboard</h2>
</header>
<main class="mt-6">
    <section class="space-y-4">
        <h3 class="text-md font-semibold">Grupos</h3>
        <div class="overflow-x-auto">
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Route</th>
                        <th>#Students</th>
                        <th>#Parents</th>
                        <th>Schedule</th>
                        <th>It is public</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for group in groups %}
                    <tr>
                        <th>{{ group.id }}</th>
                        <td>{{ group.route }}</td>
                        <td>{{ group.students }}</td>
                        <td>{{ group.parents }}</td>
                        <td>{{ group.schedule }}</td>
                        <td>
                            {% if group.isPublic %}
                            <a href="{{ url_for('group.changeVisibility', id=group.id) }}"
                                class="btn btn-warning btn-xs">Ocultar</a>
                            {% else %}
                            <a href="{{ url_for('group.changeVisibility', id=group.id) }}"
                                class="btn btn-primary btn-xs">Publicar</a>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ url_for('group.delete', id=group.id) }}" class="btn btn-error btn-xs">Borrar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
</main>
{% endblock %}